#!/bin/bash

# up -- Debian/Ubuntu Update Tool (V 1.4)

# filename          : up
# description       : Advanced command to fully update system
# author            : Jeremy Noverraz
# email             : jeremy.noverraz@gmail.com
# version           : 1.4
# usage             : up
# notes             : Adding the option "--clean" will remove orphaned packages and auto-clean the apt cache.
#                     Adding the option "--remove" will just remove orphaned packages and leave the apt cache alone.
# license           : GNU/General Public License version 2.0
#==============================================================================


# check for less program and install if not exist

dpkg -l | grep -qw less || sudo apt install less -yy

# Set BASH to quit script and exit on errors : 

set -e 

# ASCII header ( Electronic )

header(){
    cat << _EOF_

 ▄         ▄  ▄▄▄▄▄▄▄▄▄▄▄                         ▄               ▄          ▄▄▄▄           ▄         ▄ 
▐░▌       ▐░▌▐░░░░░░░░░░░▌                       ▐░▌             ▐░▌       ▄█░░░░▌         ▐░▌       ▐░▌
▐░▌       ▐░▌▐░█▀▀▀▀▀▀▀█░▌                        ▐░▌           ▐░▌       ▐░░▌▐░░▌         ▐░▌       ▐░▌
▐░▌       ▐░▌▐░▌       ▐░▌                         ▐░▌         ▐░▌         ▀▀ ▐░░▌         ▐░▌       ▐░▌
▐░▌       ▐░▌▐░█▄▄▄▄▄▄▄█░▌      ▄▄▄▄▄▄▄▄▄▄▄         ▐░▌       ▐░▌             ▐░░▌         ▐░█▄▄▄▄▄▄▄█░▌
▐░▌       ▐░▌▐░░░░░░░░░░░▌     ▐░░░░░░░░░░░▌         ▐░▌     ▐░▌              ▐░░▌         ▐░░░░░░░░░░░▌
▐░▌       ▐░▌▐░█▀▀▀▀▀▀▀▀▀       ▀▀▀▀▀▀▀▀▀▀▀           ▐░▌   ▐░▌               ▐░░▌          ▀▀▀▀▀▀▀▀▀█░▌
▐░▌       ▐░▌▐░▌                                       ▐░▌ ▐░▌                ▐░░▌                   ▐░▌
▐░█▄▄▄▄▄▄▄█░▌▐░▌                                        ▐░▐░▌             ▄▄▄▄█░░█▄▄▄       ▄        ▐░▌
▐░░░░░░░░░░░▌▐░▌                                         ▐░▌             ▐░░░░░░░░░░░▌     ▐░▌       ▐░▌
 ▀▀▀▀▀▀▀▀▀▀▀  ▀                                           ▀               ▀▀▀▀▀▀▀▀▀▀▀       ▀         ▀ 
                                                                                                        
_EOF_
}

update() {
    header
    echo -e "\n\e[1;32;1mStarting full system update ...\e[0m\n"
    sudo apt-get update -yy
    sudo apt-get dist-upgrade -yy
    sudo apt-get full-upgrade -yy
}

updateQuiet() {
    echo -e "\n\e[1;32;1mStarting full system update ...\e[0m\n" 2>&1 >/dev/null
    sudo apt-get update -yy 2>&1 >/dev/null
    sudo apt-get dist-upgrade -yy 2>&1 >/dev/null
    sudo apt-get full-upgrade -yy 2>&1 >/dev/null
}

clean() {
    echo -e "\n\e[1;32;1mRemoving apt cache packages that can no longer be downloaded ...\e[0m\n"
    sudo apt-get --purge autoremove -yy
    sudo apt-get autoclean -yy
}

cleanQuiet() {
    echo -e "\n\e[1;32;1mRemoving apt cache packages that can no longer be downloaded ...\e[0m\n" 2>&1 >/dev/null
    sudo apt-get --purge autoremove -yy 2>&1 >/dev/null
    sudo apt-get autoclean -yy 2>&1 >/dev/null
}

remove() {
    header
    echo -e "\n\e[1;32;1mRemoving orphaned packages ...\e[0m\n" 
    sudo apt autoremove -yy
    sudo apt remove --purge $(dpkg -l | grep "^rc" | awk '{print $2}') -yy 
}

removeQuiet() {
    echo -e "\n\e[1;32;1mRemoving orphaned packages ...\e[0m\n" 2>&1 >/dev/null
    sudo apt autoremove -yy 2>&1 >/dev/null
    sudo apt remove --purge $(dpkg -l | grep "^rc" | awk '{print $2}') -yy 2>&1 >/dev/null
}


leaveClean(){
#cyberlarge
cat << _EOF_

 _______        _______ _______ __   _      _______  _____  _______  _____         _______ _______ _______ ______         /
 |       |      |______ |_____| | \  |      |       |     | |  |  | |_____] |      |______    |    |______ |     \       / 
 |_____  |_____ |______ |     | |  \_|      |_____  |_____| |  |  | |       |_____ |______    |    |______ |_____/      .  
                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                 
_EOF_
exit
}

leaveUpdate(){
#cyberlarge
cat << _EOF_

 _     _  _____  ______  _______ _______ _______      _______  _____  _______  _____         _______ _______ _______ ______         /
 |     | |_____] |     \ |_____|    |    |______      |       |     | |  |  | |_____] |      |______    |    |______ |     \       / 
 |_____| |       |_____/ |     |    |    |______      |_____  |_____| |  |  | |       |_____ |______    |    |______ |_____/      .  
                                                                                                                                                                                                                                                                         
                                                                                                                                     
_EOF_
exit
}

leaveRemove(){
#cyberlarge
cat << _EOF_

  ______ _______ _______  _____  _    _ _______      _______  _____  _______  _____         _______ _______ _______ ______         /
 |_____/ |______ |  |  | |     |  \  /  |______      |       |     | |  |  | |_____] |      |______    |    |______ |     \       / 
 |    \_ |______ |  |  | |_____|   \/   |______      |_____  |_____| |  |  | |       |_____ |______    |    |______ |_____/      .  
                                                                                                                                    
                                                                                                                          
_EOF_
exit
}

help() {
    less << _EOF_

    Press "q" to leave this page.


    up is a tool that automates the update procedure for Debian and Ubuntu based Linux systems.

    Commands: 

    up                  Full system update.

    Running "up" with no options will update the apt chache and then perform a full distribution update automatically.

    Options : 

    COMMAND[--OPTION]

    up --clean          Full system update with cleanup.

    Adding the --clean option will invoke the apt commands to search for and remove
    locally cached packages that are no longer in the repositories and also remove
    orphaned packages that are no longer needed by programs.

    up --remove         The "--remove" option only removes orphaned packages, leaving the apt cache alone.

    up --quiet         The "--quiet" command is exactly the same as the "up" command, but without stdout

    up --quiet-clean   The "--quiet-clean" command is exactly the same as the "up --clean" command, but without stdout

    up --quiet-remove  The "--quiet-remove" command is exactly the same as the "up --remove" command, but without stdout

    up --help           Show this help page.
_EOF_
}

# Start here

#Update and clean

case $1 in
  --clean)
    update
    clean
    leaveClean
    ;;
  --help)
    help
    exit
    ;;
  --remove)
    remove
    leaveRemove
    ;;
  --quiet)
    updateQuiet
    exit
    ;;
  --quiet-clean)
    updateQuiet
    cleanQuiet
    exit
    ;;
  --quiet-remove)
    removeQuiet
    exit
    ;;
esac

#Check for invalid argument
#       -n STRING   -> the length of STRING is nonzero // man test for more info

if [ -n "$1" ]; then
echo -e "Error: Invalid argument. Try 'up --help for more info\n" >&2
exit 1
fi 

# No arguments, just "up"

update
leaveUpdate
